### ISSUE TITLE
Problème d'authentification

### ISSUE THREAD

**Issue by JWillow** [dunod-docker/vagrant-box#1]
Bonjour,

Je suis un lecteur du livre Docker : Pratique des architectures à base de ...
J'ai suivi la procédure vagrant pour monter mon environnement de test par rapport aux exemples du livre.
Il semble y avoir un souci avec le mot de passe associé au user "vagrant". Que ce soit le process vagrant ou moi-même manuellement via virtualbox, impossible de me connecter à la VM avec le mot de passe "vagrant"

traces :

  default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

Cordialement,

**Comment by tgarlot** [comment]
Bonjour,

Cela resemble fortement à un problème de clé. Utilisez-vous Windows / Mac OSX? 
Une idée (assez dur d'aider plus sans avoir la configuration exacte de Vagrant sur votre poste):
- Supprimer la clé privée qui se trouve dans un sous répertoire de votre VagrantFile dans .vagrant/machines/default/virtualbox/private_key. 
- Puis utiliser la commande "vagrant ssh-config" (avec la VM démarrée)
- Puis redémarrer la VM avec "vagrant halt" puis "vagrant up"

D'autres idées sur ce post Stackoverflow: http://stackoverflow.com/questions/22922891/vagrant-ssh-authentication-failure

Cordialement
